language: node_js
node_js:
    - "0.11"

before_script:
    - npm install

script:
    - node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=PhantomJS
